name: Release

on:
  push:
    tags:
      - 'v*'
env:
  HOST: "45.67.59.104"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        working-directory: ./
        run: | 
          mkdir dist 
          touch dist/index.html 
          date >> dist/index.html

      - name: Prepare SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: copy files
        run: |
          echo "Start deploy to: ${HOST}"
          scp -r -C dist/* root@${HOST}:/var/www/html

      - name: Finish Message
        run: |
          echo "deploy completed"

      - name: Notify On Error
        if: ${{ failure() || cancelled() }}
        run: |
          echo "deploy error"
